"""empty message

Revision ID: 26289acaba84
Revises: 5f18036994da
Create Date: 2022-03-24 08:31:41.245429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26289acaba84'
down_revision = '5f18036994da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projeto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projeto')
    # ### end Alembic commands ###
